# https://github.com/helios-ag/FMElfinderBundle
fm_elfinder:
    instances:
        default:
            locale: '%locale%'
            editor: ckeditor
            include_assets: true
            relative_path: true
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['all']
#                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
#                        upload_deny: ['all']
#                        upload_max_size: 2M
        image:
            locale: '%locale%'
            editor: ckeditor
            include_assets: true
            relative_path: true
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M
