vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: '%app.path.upload.images%'
            upload_destination: '%kernel.project_dir%/public%app.path.upload.images%'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            directory_namer:
                service: vich_uploader.directory_namer_subdir
                options: {chars_per_dir: 1, dirs: 2}
