vich_uploader:
    mappings:
        vehicletype.image:
            #            directory_namer: wicrew.circuit.directory_namer.pdf
            directory_namer:
                service: vich_uploader.directory_namer_subdir
                options: {chars_per_dir: 1, dirs: 2}
            namer: vich_uploader.namer_uniqid
            uri_prefix:         '/uploads/vehicletype/images'
            upload_destination: '%kernel.project_dir%/public/uploads/vehicletype/images'
