<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    Symfony\Bundle\WebServerBundle\WebServerBundle::class => ['dev' => true],
    FOS\UserBundle\FOSUserBundle::class => ['all' => true],
    EasyCorp\Bundle\EasyAdminBundle\EasyAdminBundle::class => ['all' => true],
    FOS\CKEditorBundle\FOSCKEditorBundle::class => ['all' => true],
    FM\ElfinderBundle\FMElfinderBundle::class => ['all' => true],
    Vich\UploaderBundle\VichUploaderBundle::class => ['all' => true],
    Knp\Bundle\PaginatorBundle\KnpPaginatorBundle::class => ['all' => true],
    App\Wicrew\CoreBundle\WicrewCoreBundle::class => ['all' => true],
    App\Wicrew\CronBundle\WicrewCronBundle::class => ['all' => true],
    App\Wicrew\PartnerBundle\WicrewPartnerBundle::class => ['all' => true],
    App\Wicrew\VehicleTypeBundle\WicrewVehicleTypeBundle::class => ['all' => true],
    App\Wicrew\VehicleBundle\WicrewVehicleBundle::class => ['all' => true],
    App\Wicrew\ActivityBundle\WicrewActivityBundle::class => ['all' => true],
    App\Wicrew\AdditionalFeeBundle\WicrewAdditionalFeeBundle::class => ['all' => true],
    App\Wicrew\AddonBundle\WicrewAddonBundle::class => ['all' => true],
    App\Wicrew\ProductBundle\WicrewProductBundle::class => ['all' => true],
    App\Wicrew\SaleBundle\WicrewSaleBundle::class => ['all' => true],
    App\Wicrew\BlockBundle\WicrewBlockBundle::class => ['all' => true],
    App\Wicrew\PageBundle\WicrewPageBundle::class => ['all' => true],
    App\Wicrew\ReportBundle\WicrewReportBundle::class => ['all' => true],
    App\Wicrew\SystemConfigurationBundle\WicrewSystemConfigurationBundle::class => ['all' => true],
    Knp\Bundle\SnappyBundle\KnpSnappyBundle::class => ['all' => true],
    App\Wicrew\DateAvailability\WicrewDateAvailability::class => ['all' => true],
];
